### ISSUE TITLE
Test @rpch/ethers integration into BW

### ISSUE THREAD

**Issue by nionis** [Rpc-h/extension-block-wallet#4]
### Description

We need to ensure that there are no unexpected issues after running the extension for a longtime, browser restart, etc.
Create a testing list to check various edge cases that may happen during normal user use of the extension.
Perform testing list and document your findings.

### Relevant issues

- create testing list
- perform testing list
- document findings

### Definition of DONE

Once findings have been documented as a comment / link to doc.

**Comment by ItsLuized** [comment]
1. Make normal transaction
    - OK
2. Restart browser and use BW to make a transaction:
    - OK
3. Make a transaction and restart browser while on transaction
    - If browser is restart while on the sending transactions screen, transaction doesn’t go (expected)
    - If we wait a few seconds, transaction goes OK
4. Remove Extension and install again
    - Everything OK
5. Receive transaction
    - Transaction and balance is updated

**Comment by nionis** [comment]
Thanks @ItsLuized
