### ISSUE TITLE
Provider down when connecting initially to gnosis

### ISSUE THREAD

**Issue by diegoalzate** [Rpc-h/extension-block-wallet#6]
## Overview
Provider down error shows up when selecting gnosis chain for the first 5s.

Steps to reproduce:
- run bw locally with sandbox
- choose gnosis chain instead of mainnet

![CleanShot 2023-02-01 at 14 56 33](https://user-images.githubusercontent.com/22416585/216149828-5de7e4f9-e1d2-42e0-8b19-3be6999482ef.png)

**Comment by nionis** [comment]
No longer happens in our new PR
